---
title: "Influence of maladaptive migrants on a dying population"
author: "Florin Suter, Balz Fuchs, Felix Rentschler"
date: "WIP WIP WIP WIP WIP WIP WIP"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

# Introduction

In conservation we often see introduction of migrants as a way to save a doomed population. There are many examples of this like for example the rescue of the Florida panther (*Puma concolor coryi*) population by introducing panthers from other regions to increase the populations gene pool and thus rescue them from inbreeding depression.

However, in this model we thought about a diploid populations (aa) that is maladapted to its environment and can only become a growing population by acquiring a certain beneficial mutation (AA). Our hypothetical scientists are attempting to save the population by introducing migrants from a source population that doesn't carry the beneficial allele and thus is also maladaptive. Additionally there is a second problem, the beneficial allele is recessive meaning that only a homozygote mutant can reap the benefits of the mutation. In our model we hoped to see the impact of a migrating deleterious genotype on the extinction and rescue probabilities of our population.

# Methods

For this model all coding was done using the language r. For the code base r was sufficient however for the visualization of the results packages such as ggplot were used to increase legibility.

## Source code

The base source code used for the further coding of the model was provided by the theoretical ecology and evolution (TEE) research group. The code models a doomed population that will go extinct but can be rescued by the fixation of a beneficial mutation. It simulates this for as many generations as are input. The source code can be found on the TEE teams platform. The rest of the code was written by us.

## New code (--\> change the name)

### Simulation of one generation

In a first step one generation has to be simulated. As the population is diploid there are three starting populations that are set as N_aa = 1000, N_Aa = 0, and N_AA = 0. As there is a fitness difference between the different genotypes these had to be defined as well. For the fitness of the different genotypes we chose fitnessaa = 0.9, fiitnessAa = 0.9, and fitnessAA = 1.1. Both the selection coefficient and the decay rate are contained in the fitnesses in order to keep the number of parameters to a minimum. The next parameter is avagmigrants. This parameter represents them mean number of migrants that enter the system in the given generation. Here it is important to note that this is the parameter that is varied. We tested the model with zero to ten migrants. The genotype of these migrants is always the maladptive aa genotype. The final parameter defined for this function is the mutation rate mut_rate = 0.0005. This mutation rate was chosen arbitrarily in a way that the average number of mutants per generation isn't over one.

The function assumes a Hardy-Weinberg equilibrium. The parts of the code dealing with this will be described below. Some variables are mentioned below and are not explained. For these please see the code provided in the attachment.

1.  The total number of a and A alleles are calculated:

    *a_tot = 2\*N_aa+N_Aa*

2.  Number of mutations from A to a and back are calculated:

    *a_to_A\_mut = min(rpois(1,a_tot\*mut_rate),a_tot)*

3.  p and q are defined as:

    *p = (a_tot+A_to_a\_mut-a_to_A\_mut)/(2\*tot_pop)*

    *q = 1-p*

4.  Calculate frequency of the genotypes in the next generation. This is where selection takes place

    *det_aa_next = (p\^2)\*fitnessaa/avg_fit*

5.  Draw the true number of offspring. Note that migrants are only added to the aa offspring as this is the maladaptive genotype.

    *offsp_aa = rpois(1, next_gen_tot_pop\*det_aa_next) + aa_migrants*

    *offsp_Aa = rpois(1, next_gen_tot_pop\*det_Aa_next)*

    *offsp_AA = rpois(1, next_gen_tot_pop\*det_AA_next)*

### Simulation of population until one of three conditions is reached

Here the code is run until one of three conditions is reached. The first condition is that the population reaches 1.5 times its starting size. This is seen as successfully escaping extinction and becoming a growing, self sustaining population. The second condition is that the population goes extinct. As a population with a continuous stream of incoming migrants never stays at zero individuals for long, extinction is defined as 10\* the number of migrants per generation. The final condition that can be reached is that the population surpasses t_max = 10000 generations. This is a fail safe that ensures that the simulation stops at some point and does not run indefinitely.

This function contains most of the same parameters as the function explained above. As this function runs for more than just one generation the labels for N_aa, N_Aa, and N_AA have been changed to N_init_aa, N_init_Aa, and N_init_AA. The only new parameter is the aforementioned t_max which represents the maximum number of generations that the model should simulate. The important steps of the function will once again be outlined below. As above some steps will be left out and can be found down below in the attachment.

1.  The for-loop runs for t_max generations generating t_max generations which are continuously added to one matrix; pop_vector.

2.  Next we have a nestled if command. This loop breaks off the simulation if a population size is generated, that is more than 1.5 times the size of the initial population size.

3.  The final else if command breaks of the simulation if the minimal populations size goes below the threshold of 2\*avgmigrants at which point the population is assumed to be functionally extinct.
