---
title: "R Notebook"
output: html_notebook
---


```{r}
simulate_one_gen_migrants_A <- function(N_a, N_A, decay_rate, sel_coeff, mut_rate,lambda_A) {
  # draw offspring according to Poisson distribution
  offsp_a <- rpois(1, N_a * (1-decay_rate))
  offsp_A <- rpois(1, N_A * (1-decay_rate+sel_coeff))
  # draw new mutants according to Poisson distribution
  mut_a_to_A <- rpois(1, offsp_a * mut_rate)
  mut_A_to_a <- rpois(1, offsp_A * mut_rate)
  # draw migrants for each genotype
  #migrants_a <- rpois(1,lambda_a)
  migrants_A <- rpois(1,lambda_A)
  # determine new population sizes of wild type and mutant
  N_a_new <- max(offsp_a - mut_a_to_A, 0) + mut_A_to_a
  N_A_new <- max(offsp_A - mut_A_to_a, 0) + mut_a_to_A + migrants_A
  
  return(c(N_a_new, N_A_new))
}

```

```{r}
#And then we continue with simulating multiple generations:
simulate_pop_migrants_nur_A <- function(N0_a, N0_A, decay_rate, sel_coeff, migrants_A, mut_rate, t_max) {
  # Create the vector in which to save the results
  pop_vector <- c(N0_a, N0_A)
  # initiate the variables
  pop_new <- c(N0_a, N0_A)
  for(i in 1:t_max+1){
    pop_new <- simulate_one_gen_migrants_A(pop_new[1],pop_new[2], decay_rate, sel_coeff, mut_rate, migrants_A)
    pop_vector <- rbind(pop_vector, pop_new)
    if (pop_new[1]+pop_new[2]>=5*(N0_a+ N0_A) | pop_new[1]+pop_new[2]==0) break
     }

  # define the row and column names of the output vector
  rownames(pop_vector) <- (0:t_max)[1:length(pop_vector[,1])] # note that the vector has to be cut if the simulation stopped early
  colnames(pop_vector) <- c("a","A")
  # return the result
  return(pop_vector)	
}
```

```{r}
max_gen <- 1000
N0_a <- 100
N0_A <- 0
decay_rate <- 0.1
sel_coef <- 0.2
migrants_A <- 5
mut_rate <- 0
# create your simulation data
output <- simulate_pop_migrants_nur_a(N0_a, N0_A, decay_rate, sel_coef, migrants_A,mut_rate,max_gen)
# plot the output - note that the plot range and the x axis have to be adjusted based on the length of the table
# determine x axis range 
print(head(output))
x_range <- 0:(length(output[,1])-1)
# this plots the total population size
plot(x_range,output[,1]+output[,2],type='l',ylim=c(0,max(output[,1]+output[,2])),xlab = "Generation",ylab = "Population size")
# add number of wild type individuals
lines(x_range,output[,1], col="blue")
# add number of mutant individuals
lines(x_range,output[,2], col="red")
````
