---
title: "R Notebook"
output: html_notebook
---

This is the data analysis part juhuuu.
first we load the data

```{r}
# Analysis for the presentation
setwd("C:/Users/flori/OneDrive/Dokumente/Studium/THEE researchpractical/TEE_Shadowvalley")
# get the data frame
df <- read.csv("Data_29_10_2024.csv")
```
then we prepare it for our main plot:
```{r}
# make a matrix with the amount of each outcome per mig rate
mig <- matrix(NA,nrow = 3, ncol = 11)
for (i in 0:(ncol(mig)-1)){
  mig[,i+1] <- c(sum(df$success[df$migration_per_gen == i & df$fitnessAa ==0.9] == "extinction"),
                 sum(df$success[df$migration_per_gen == i & df$fitnessAa ==0.9] == "medium"),
                 sum(df$success[df$migration_per_gen == i & df$fitnessAa ==0.9] == "reached_max"))
}
# translate it into %
mig <- mig/20
```
after that we plot the graph:
```{r}
library("viridis")
colors <- viridis(3,begin = 0.2,end = 0.8)
par(mfrow = (c(1,2)))
barplot(mig, col = colors, names.arg = 0:10, xlab = "mean migrants/ generation", ylab ="proportion in %")
barplot(mig[3,], names.arg = 0:10, col = colors[3],xlab = "mean migrants/ generation", ylab ="proportion in %")
legend("topright", legend = c("Extinction", "Persistence", "Reached Max"), fill = colors, bty = "n", cex = 0.8)
```
now we create a matrix with the outcomes of the other heterozygote modes
```{r}
mig1and1.1 <- matrix(NA,nrow = 3, ncol = 22)
x <- 0
for (j in c(1,1.1)){
  for (i in 0:(ncol(mig)-1)){
    mig1and1.1[,i+1+x] <- c(sum(df$success[df$migration_per_gen == i & df$fitnessAa ==j] == "extinction"),
                      sum(df$success[df$migration_per_gen == i & df$fitnessAa ==j] == "medium"),
                      sum(df$success[df$migration_per_gen == i & df$fitnessAa ==j] == "reached_max"))
  }
  x <- x+11
}
mig1and1.1 <- mig1and1.1/10
```

```{r}
library("viridis")
colors <- viridis(3,begin = 0.2,end = 0.8)
par(mfrow = c(1, 1), mar = c(5, 4, 4, 6), oma = c(0, 0, 0, 6))
barplot(mig1and1.1[,1:11], col = colors, names.arg = 0:10, xlab = "mean migrants/ generation", ylab ="proportion in %", main = "Heterozygotes with intermediate fitness")
par(xpd = TRUE)  # Allows plotting outside the plot region
legend("right", inset = -0.3, legend = c("Extinction", "Persistence", "Reached Max"), fill = colors, bty = "n", cex = 0.8)
```

Dominant mutation
```{r}
library("viridis")
colors <- viridis(3,begin = 0.2,end = 0.8)
par(mfrow = c(1, 1), mar = c(5, 4, 4, 6), oma = c(0, 0, 0, 6))
barplot(mig1and1.1[,12:22], col = colors, names.arg = 0:10, xlab = "mean migrants/ generation", ylab ="proportion in %", main = "Dominant mutation")
par(xpd = TRUE)  # Allows plotting outside the plot region
legend("right", inset = -0.3, legend = c("Extinction", "Persistence", "Reached Max"), fill = colors, bty = "n", cex = 0.8)
```

```{r}
library(ggplot2)
library(dplyr)

# Filter the data for fitnessAa == 0.9
filtered_data <- df %>%
  filter(fitnessAa == 0.9) %>%
  mutate(final_pop_size = ifelse(final_pop_size == 0,0.1, final_pop_size))

line_data <- data.frame(
  migration_per_gen = 1:11,
  final_pop_size = 2 * (0:10)
) %>%
  mutate(final_pop_size = ifelse(final_pop_size == 0, 0.1, final_pop_size))

# Create a violin plot of final_pop_size against migration_per_gen
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = final_pop_size)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) +  # Violin plot for distribution
  scale_y_log10()+
  labs(x = "Mean Migrants per Generation", y = "Final Population Size",
       title = "Distribution of Final Population Size by Migration per Generation\n(fitnessAa = 0.9)") +
  theme_minimal()+
  geom_segment(data = line_data, 
               aes(x = migration_per_gen-0.25, 
                   xend = migration_per_gen+0.25, 
                   y = final_pop_size, 
                   yend = final_pop_size), 
               color = "red", 
               size = 1)

```

```{r}
library(ggplot2)
library(dplyr)

# Filter the data for fitnessAa == 0.9
filtered_data <- df %>%
  filter(fitnessAa == 0.9)

# Create a violin plot of final_pop_size against migration_per_gen
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = p_final)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) +  # Violin plot for distribution
  labs(x = "Mean Migrants per Generation", y = "Final wt Allele Frequency",
       title = "Distribution of Final Allele Frequency by Migration per Generation\n Populations with final Population size = 0 not included \n fitnessAa = 0.9") +
  theme_minimal()
```


```{r}
library(ggplot2)
library(dplyr)

# Filter the data for fitnessAa == 0.9
filtered_data <- df %>%
  filter(fitnessAa == 1)

# Create a violin plot of final_pop_size against migration_per_gen
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = p_final)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) +  # Violin plot for distribution
  labs(x = "Mean Migrants per Generation", y = "Final wt Allele Frequency",
       title = "Distribution of Final Allele Frequency by Migration per Generation\n Populations with final Population size = 0 not included\n fitnessAa = 1") +
  theme_minimal()



```
```{r}
library(ggplot2)
library(dplyr)

# Filter the data for fitnessAa == 0.9
filtered_data <- df %>%
  filter(fitnessAa == 1.1)

# Create a violin plot of final_pop_size against migration_per_gen
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = p_final)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) +  # Violin plot for distribution
  labs(x = "Mean Migrants per Generation", y = "Final wt Allele Frequency",
       title = "Distribution of Final Allele Frequency by Migration per Generation\n Populations with final Population size = 0 not included\n fitnessAa = 1.1") +
  theme_minimal()



```

```{r}
df3to7 <- read.csv("eva_data_slay.csv")
mig3to7 <- matrix(NA, nrow = 3, ncol = 5)
colnames(mig3to7) <- 3:7
rownames(mig3to7) <- c("extinction","medium","reached_max")
for (i in 1:ncol(mig3to7)){
  mig3to7[,i] <- c(sum(df3to7$success[df3to7$migration_per_gen == i+2] == 1),
               sum(df3to7$success[df3to7$migration_per_gen == i+2] == 2),
               sum(df3to7$success[df3to7$migration_per_gen == i+2] == 3))
}
mig3to7 <- mig3to7/100
par(mfrow = c(1, 2), mar = c(5, 4, 4, 6), oma = c(0, 0, 0, 6))
barplot(mig3to7, col = colors, names.arg = 3:7, xlab = "mean migrants/ generation", ylab ="proportion in %")
barplot(mig3to7[3,], names.arg = 3:7, col = colors[3],xlab = "mean migrants/ generation", ylab ="proportion in %")
par(xpd = TRUE)  # Allows plotting outside the plot region
legend("right", inset = -1, legend = c("Extinction", "Persistence", "Reached Max"), fill = colors, bty = "n", cex = 0.8)

```

```{r}
library(ggplot2)
library(dplyr)

# Filter data where success == 3
filtered_data <- df3to7 %>%
  filter(success == 3)
summary_data <- filtered_data %>%
  group_by(migration_per_gen) %>%
  summarise(
    count = n()  # Count of values in each category
  )
# Create the plot
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = number_of_generations)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) + 
  labs(x = "Migration per Generation", y = "Number of Generations",
       title = "numbers of generation until maximum was reached") +
  geom_hline(yintercept = 10000, color = "red", linetype = "dashed", size = 1) +
  geom_text(data = summary_data, aes(x = factor(migration_per_gen), y = max(filtered_data$number_of_generations) * 1.05, 
                                     label = paste("n =", count)), 
            color = "black", size = 3) +
  theme_minimal()
```

```{r}
library(ggplot2)
library(dplyr)

# Filter data where success == 3
filtered_data <- df %>%
  filter(success == "reached_max" & fitnessAa == 0.9)
summary_data <- filtered_data %>%
  group_by(migration_per_gen) %>%
  summarise(
    count = n()  # Count of values in each category
  )
# Create the plot
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = number_of_generations)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) + 
  labs(x = "Migration per Generation", y = "Number of Generations",
       title = "numbers of generation until maximum was reached, fitnessAa = 0.9") +
  scale_y_log10()+
  geom_text(data = summary_data, aes(x = factor(migration_per_gen), y = max(filtered_data$number_of_generations) * 1.05, 
                                     label = paste("n =", count)), 
            color = "black", size = 3) +
  theme_minimal()
```

```{r}
library(ggplot2)
library(dplyr)

# Filter data where success == 3
filtered_data <- df %>%
  filter(success == "reached_max" & fitnessAa == 1)
summary_data <- filtered_data %>%
  group_by(migration_per_gen) %>%
  summarise(
    count = n()  # Count of values in each category
  )
# Create the plot
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = number_of_generations)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) + 
  labs(x = "Migration per Generation", y = "Number of Generations",
       title = "numbers of generation until maximum was reached, fitnessAa = 1") +
  scale_y_log10()+
  geom_text(data = summary_data, aes(x = factor(migration_per_gen), y = max(filtered_data$number_of_generations) * 1.05, 
                                     label = paste("n =", count)), 
            color = "black", size = 3) +
  theme_minimal()
```

```{r}
library(ggplot2)
library(dplyr)

# Filter data where success == 3
filtered_data <- df %>%
  filter(success == "reached_max" & fitnessAa == 1.1)
summary_data <- filtered_data %>%
  group_by(migration_per_gen) %>%
  summarise(
    count = n()  # Count of values in each category
  )
# Create the plot
ggplot(filtered_data, aes(x = factor(migration_per_gen), y = number_of_generations)) +
  geom_violin(fill = "skyblue", color = "darkblue", alpha = 0.6) + 
  labs(x = "Migration per Generation", y = "Number of Generations",
       title = "numbers of generation until maximum was reached, fitnessAa = 1.1") +
  scale_y_log10()+
  geom_text(data = summary_data, aes(x = factor(migration_per_gen), y = max(filtered_data$number_of_generations) * 1.05, 
                                     label = paste("n =", count)), 
            color = "black", size = 3) +
  theme_minimal()
```