setwd("C:/Users/flori/OneDrive/Dokumente/Studium/THEE researchpractical/TEE_Shadowvalley")

data <- read.csv("analysis.csv")
mig0.extinct <- (sum(data$success[data$migration == 0] == "extinction"))
mig0.medium <- (sum(data$success[data$migration == 0] == "medium"))
mig0.max <- (sum(data$success[data$migration == 0] == "reached_max"))
mig1.extinct <- (sum(data$success[data$migration == 1] == "extinction"))
mig1.medium <- (sum(data$success[data$migration == 1] == "medium"))
mig1.max <- (sum(data$success[data$migration == 1] == "reached_max"))
mig2.extinct <- (sum(data$success[data$migration == 2] == "extinction"))
mig2.medium <- (sum(data$success[data$migration ==2] == "medium"))
mig2.max <- (sum(data$success[data$migration == 2] == "reached_max"))
mig3.extinct <- (sum(data$success[data$migration == 3] == "extinction"))
mig3.medium <- (sum(data$success[data$migration == 3] == "medium"))
mig3.max <- (sum(data$success[data$migration == 3] == "reached_max"))
mig4.extinct <- (sum(data$success[data$migration == 4] == "extinction"))
mig4.medium <- (sum(data$success[data$migration == 4] == "medium"))
mig4.max <- (sum(data$success[data$migration == 4] == "reached_max"))
mig5.extinct <- (sum(data$success[data$migration == 5] == "extinction"))
mig5.medium <- (sum(data$success[data$migration == 5] == "medium"))
mig5.max <- (sum(data$success[data$migration == 5] == "reached_max"))
mig6.extinct <- (sum(data$success[data$migration == 6] == "extinction"))
mig6.medium <- (sum(data$success[data$migration == 6] == "medium"))
mig6.max <- (sum(data$success[data$migration == 6] == "reached_max"))
mig7.extinct <- (sum(data$success[data$migration == 7] == "extinction"))
mig7.medium <- (sum(data$success[data$migration == 7] == "medium"))
mig7.max <- (sum(data$success[data$migration == 7] == "reached_max"))
mig8.extinct <- (sum(data$success[data$migration == 8] == "extinction"))
mig8.medium <- (sum(data$success[data$migration == 8] == "medium"))
mig8.max <- (sum(data$success[data$migration == 8] == "reached_max"))
mig9.extinct <- (sum(data$success[data$migration == 9] == "extinction"))
mig9.medium <- (sum(data$success[data$migration == 9] == "medium"))
mig9.max <- (sum(data$success[data$migration == 9] == "reached_max"))
mig10.extinct <- (sum(data$success[data$migration == 10] == "extinction"))
mig10.medium <- (sum(data$success[data$migration == 10] == "medium"))
mig10.max <- (sum(data$success[data$migration == 10] == "reached_max"))
mig0 <- c(mig0.extinct,mig0.medium,mig0.max)/(mig0.extinct+mig0.medium+mig0.max)
mig1 <- c(mig1.extinct,mig1.medium,mig1.max)/(mig1.extinct+mig1.medium+mig1.max)
mig2 <- c(mig2.extinct,mig2.medium,mig2.max)/(mig2.extinct+mig2.medium+mig2.max)
mig3 <- c(mig3.extinct,mig3.medium,mig3.max)/(mig3.extinct+mig3.medium+mig3.max)
mig4 <- c(mig4.extinct,mig4.medium,mig4.max)/(mig4.extinct+mig4.medium+mig4.max)
mig5 <- c(mig5.extinct,mig5.medium,mig5.max)/(mig5.extinct+mig5.medium+mig5.max)
mig6 <- c(mig6.extinct,mig6.medium,mig6.max)/(mig6.extinct+mig6.medium+mig6.max)
mig7 <- c(mig7.extinct,mig7.medium,mig7.max)/(mig7.extinct+mig7.medium+mig7.max)
mig8 <- c(mig8.extinct,mig8.medium,mig8.max)/(mig8.extinct+mig8.medium+mig8.max)
mig9 <- c(mig9.extinct,mig9.medium,mig9.max)/(mig9.extinct+mig9.medium+mig9.max)
mig10 <- c(mig10.extinct,mig10.medium,mig10.max)/(mig10.extinct+mig10.medium+mig10.max)

mig <- matrix(c(mig0,mig1,mig2,mig3,mig4,mig5,mig6,mig7,mig8,mig9,mig10),nrow = 3, ncol = 11)
install.packages("viridis")
library("viridis")
colors <- magma(3,begin = 0.2,end = 0.8)
barplot(mig, col = colors)

max_pop_size <- matrix(c(data$maximal_pop_size[data$migration==0],data$maximal_pop_size[data$migration==1],data$maximal_pop_size[data$migration==2],data$maximal_pop_size[data$migration==3],data$maximal_pop_size[data$migration==4],data$maximal_pop_size[data$migration==5],data$maximal_pop_size[data$migration==6],data$maximal_pop_size[data$migration==7],data$maximal_pop_size[data$migration==8],data$maximal_pop_size[data$migration==9],data$maximal_pop_size[data$migration==10]),ncol = 11)
colnames(max_pop_size) <- 0:10
barplot(max_pop_size)

mean(data$simulated_gen[data$migration==10])
